export const theme = {
  ltr: "ltr",
  rtl: "rtl",
  root: "editor-root",
  placeholder: "editor-placeholder",
  paragraph: "editor-paragraph",
  quote: "editor-quote",
  heading: {
    h1: "editor-heading-h1",
    h2: "editor-heading-h2",
    h3: "editor-heading-h3",
    h4: "editor-heading-h4",
    h5: "editor-heading-h5",
    h6: "editor-heading-h6",
  },
  list: {
    nested: {
      listitem: "editor-list-nested-listitem",
    },
    ol: "editor-list-ol",
    ul: "editor-list-ul",
    listitem: "editor-listitem",
  },
  image: "editor-image",
  media: {
    image: "editor-media-image",
    figcaption: "editor-media-figcaption",
    frame: "editor-media-frame",
    fallback: "editor-media-fallback",
    fallbackLine: "editor-media-fallback-line",
    fallbackLineShort: "editor-media-fallback-line-short",
    fallbackLineTitle: "editor-media-fallback-line-title",
    tweetPlaceholder: "editor-tweet-placeholder",
    tweetPlaceholderBody: "editor-tweet-placeholder-body",
    tweetPlaceholderEyebrow: "editor-tweet-placeholder-eyebrow",
    tweetPlaceholderText: "editor-tweet-placeholder-text",
    tweetPlaceholderLink: "editor-tweet-placeholder-link",
    loading: "editor-media-loading",
    loadingText: "editor-media-loading-text",
    aspectVideo: "editor-media-aspect-video",
    youtube: "editor-youtube",
    tweet: "editor-tweet",
    overlay: "editor-media-overlay",
  },
  link: "editor-link",
  table: "editor-table",
  tableWrapper: "editor-table-wrapper",
  tableCell: "editor-table-cell",
  tableCellHeader: "editor-table-cell-header",
  tableCellSelected: "editor-table-cell-selected",
  tableCellContent: "editor-table-cell-content",
  tableBody: "editor-table-body",
  decoratorContents: "editor-decorator-contents",
  imageDecoratorContents: "editor-image-decorator-contents",
  hrBlock: "editor-hr-block",
  hrInner: "editor-hr-inner",
  hrSelected: "editor-hr-selected",
  hr: "editor-hr",
  checklist: {
    item: "editor-checklist-item",
    itemChecked: "editor-checklist-item-checked",
    checkbox: "editor-checklist-checkbox",
  },
  embedBlock: {
    base: "editor-embed-block",
    focus: "editor-resizable-node-selected",
  },
  resizable: {
    node: "editor-resizable-node",
    frame: "editor-resizable-node-frame",
    handle: "editor-resize-handle",
    handleLeft: "editor-resize-handle-left",
    handleRight: "editor-resize-handle-right",
    handleBar: "editor-resize-handle-bar",
  },
  tableAlignment: {
    center: "editor-table-align-center",
    right: "editor-table-align-right",
  },
  text: {
    bold: "editor-text-bold",
    italic: "editor-text-italic",
    overflowed: "editor-text-overflowed",
    hashtag: "editor-text-hashtag",
    underline: "editor-text-underline",
    strikethrough: "editor-text-strikethrough",
    underlineStrikethrough: "editor-text-underline-strikethrough",
    code: "editor-text-code",
  },
  code: "editor-code-block",
  codeLanguage: "editor-code-language",
  codePre: "editor-code-pre",
  codeContent: "editor-code-content",
  codeHighlight: {
    atrule: "code-token-atrule",
    attr: "code-token-attr",
    "attr-name": "code-token-attr",
    "attr-value": "code-token-string",
    boolean: "code-token-boolean",
    builtin: "code-token-builtin",
    cdata: "code-token-cdata",
    char: "code-token-char",
    class: "code-token-class",
    "class-name": "code-token-class-name",
    "known-class-name": "code-token-class-name",
    "maybe-class-name": "code-token-class-name",
    comment: "code-token-comment",
    constant: "code-token-constant",
    deleted: "code-token-deleted",
    doctype: "code-token-doctype",
    entity: "code-token-entity",
    function: "code-token-function",
    important: "code-token-important",
    inserted: "code-token-inserted",
    keyword: "code-token-keyword",
    namespace: "code-token-namespace",
    number: "code-token-number",
    operator: "code-token-operator",
    prolog: "code-token-prolog",
    property: "code-token-property",
    punctuation: "code-token-punctuation",
    "template-punctuation": "code-token-string",
    "template-string": "code-token-string",
    parameter: "code-token-variable",
    regex: "code-token-regex",
    selector: "code-token-selector",
    string: "code-token-string",
    symbol: "code-token-symbol",
    tag: "code-token-tag",
    url: "code-token-url",
    variable: "code-token-variable",
  },
};

export default theme;
